<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('siswa')->insert([
            [
            'user_id' => 2,
            'nama' => 'Dede Sukmadik',
            'kelas_id' => 2,
            'nis' => '123456',
            'tanggal_lahir' => '2005-01-01',
            'no_hp' => '08123456789',
            'email' => 'dede@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Ngawi No. 1',
            ],
            [
            'user_id' => 3,
            'nama' => 'Siti Nurjanah',
            'kelas_id' => 3,
            'nis' => '123457',
            'tanggal_lahir' => '2005-03-12',
            'no_hp' => '089612345678',
            'email' => 'siti@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Mawar No. 5',
            ],
            [
            'user_id' => 4,
            'nama' => 'Bambang Pamungkas',
            'kelas_id' => 2,
            'nis' => '123458',
            'tanggal_lahir' => '2005-05-22',
            'no_hp' => '081289990000',
            'email' => 'bambang@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Kenangan No. 9',
            ],
            [
            'user_id' => 5,
            'nama' => 'Ayu Lestari',
            'kelas_id' => 4,
            'nis' => '123459',
            'tanggal_lahir' => '2005-07-10',
            'no_hp' => '082112341234',
            'email' => 'ayu@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Melati No. 11',
            ],
            [
            'user_id' => 6,
            'nama' => 'Rizky Maulana',
            'kelas_id' => 3,
            'nis' => '123460',
            'tanggal_lahir' => '2005-09-30',
            'no_hp' => '087812345678',
            'email' => 'rizky@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Anggrek No. 7',
            ],
            [
            'user_id' => 7,
            'nama' => 'Nadia Zahra',
            'kelas_id' => 2,
            'nis' => '123461',
            'tanggal_lahir' => '2005-02-14',
            'no_hp' => '085612345678',
            'email' => 'nadia@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Sakura No. 4',
            ],
            [
            'user_id' => 8,
            'nama' => 'Wili Salim',
            'kelas_id' => 4,
            'nis' => '123462',
            'tanggal_lahir' => '2005-06-06',
            'no_hp' => '081345678900',
            'email' => 'wili@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Durian No. 10',
            ],
            [
            'user_id' => 9,
            'nama' => 'Putri Andini',
            'kelas_id' => 3,
            'nis' => '123463',
            'tanggal_lahir' => '2005-11-11',
            'no_hp' => '088812345678',
            'email' => 'putri@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Cemara No. 8',
            ],
            [
            'user_id' => 10,
            'nama' => 'Dani Pratama',
            'kelas_id' => 2,
            'nis' => '123464',
            'tanggal_lahir' => '2005-04-18',
            'no_hp' => '083812345678',
            'email' => 'dani@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Apel No. 2',
            ],
            [
            'user_id' => 11,
            'nama' => 'Melati Anjani',
            'kelas_id' => 4,
            'nis' => '123465',
            'tanggal_lahir' => '2005-08-25',
            'no_hp' => '082134567890',
            'email' => 'melati@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Pisang No. 6',
            ],
            [
            'user_id' => 12,
            'nama' => 'Fajar Nugroho',
            'kelas_id' => 2,
            'nis' => '123466',
            'tanggal_lahir' => '2005-10-15',
            'no_hp' => '081234567800',
            'email' => 'fajar@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Mangga No. 12',
            ],
            [
            'user_id' => 13,
            'nama' => 'Intan Permata',
            'kelas_id' => 3,
            'nis' => '123467',
            'tanggal_lahir' => '2005-12-20',
            'no_hp' => '082145678901',
            'email' => 'intan@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Kamboja No. 3',
            ],
            [
            'user_id' => 14,
            'nama' => 'Galih Prakoso',
            'kelas_id' => 4,
            'nis' => '123468',
            'tanggal_lahir' => '2005-08-02',
            'no_hp' => '083156789012',
            'email' => 'galih@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Rambutan No. 14',
            ],
            [
            'user_id' => 15,
            'nama' => 'Salsa Bilqis',
            'kelas_id' => 2,
            'nis' => '123469',
            'tanggal_lahir' => '2005-03-28',
            'no_hp' => '084167890123',
            'email' => 'salsa@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Jeruk No. 15',
            ],
            [
            'user_id' => 16,
            'nama' => 'Yoga Saputra',
            'kelas_id' => 3,
            'nis' => '123470',
            'tanggal_lahir' => '2005-06-17',
            'no_hp' => '085178901234',
            'email' => 'yoga@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Sawo No. 16',
            ],
            [
            'user_id' => 17,
            'nama' => 'Dewi Sartika',
            'kelas_id' => 4,
            'nis' => '123471',
            'tanggal_lahir' => '2005-09-09',
            'no_hp' => '086189012345',
            'email' => 'dewi@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Duku No. 17',
            ],
            [
            'user_id' => 18,
            'nama' => 'Rendi Kurniawan',
            'kelas_id' => 2,
            'nis' => '123472',
            'tanggal_lahir' => '2005-11-23',
            'no_hp' => '087190123456',
            'email' => 'rendi@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Nangka No. 18',
            ],
            [
            'user_id' => 19,
            'nama' => 'Citra Ayuningtyas',
            'kelas_id' => 3,
            'nis' => '123473',
            'tanggal_lahir' => '2005-01-30',
            'no_hp' => '088101234567',
            'email' => 'citra@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Pepaya No. 19',
            ],
            [
            'user_id' => 20,
            'nama' => 'Bagus Santoso',
            'kelas_id' => 4,
            'nis' => '123474',
            'tanggal_lahir' => '2005-04-05',
            'no_hp' => '089112345678',
            'email' => 'bagus@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Kedondong No. 20',
            ],
            [
            'user_id' => 21,
            'nama' => 'Lina Marlina',
            'kelas_id' => 2,
            'nis' => '123475',
            'tanggal_lahir' => '2005-07-13',
            'no_hp' => '081223344556',
            'email' => 'lina@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Salak No. 21',
            ],
            [
            'user_id' => 22,
            'nama' => 'Dimas Prasetyo',
            'kelas_id' => 3,
            'nis' => '123476',
            'tanggal_lahir' => '2005-10-21',
            'no_hp' => '082234455667',
            'email' => 'dimas@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Manggis No. 22',
            ],
            [
            'user_id' => 23,
            'nama' => 'Rina Oktaviani',
            'kelas_id' => 4,
            'nis' => '123477',
            'tanggal_lahir' => '2005-12-29',
            'no_hp' => '083245566778',
            'email' => 'rina@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Jambu No. 23',
            ],
            [
            'user_id' => 24,
            'nama' => 'Fikri Ramadhan',
            'kelas_id' => 2,
            'nis' => '123478',
            'tanggal_lahir' => '2005-02-07',
            'no_hp' => '084256677889',
            'email' => 'fikri@gmail.com',
            'jenis_kelamin' => 'Laki-laki',
            'alamat' => 'Jl. Sirsak No. 24',
            ],
            [
            'user_id' => 25,
            'nama' => 'Sari Melati',
            'kelas_id' => 3,
            'nis' => '123479',
            'tanggal_lahir' => '2005-05-16',
            'no_hp' => '085267788990',
            'email' => 'sari@gmail.com',
            'jenis_kelamin' => 'Perempuan',
            'alamat' => 'Jl. Markisa No. 25',
            ],
        ]);
    }
}
